### ISSUE TITLE
Версионность API и структур данных

### ISSUE THREAD

**Issue by gsbelarus** [stasgm/gdmn-mob#111]
В реальной жизни версии мобильных приложений и сервера будут различаться. Обновить все устройства и сервер одновременно физически невозможно.

Мы хотим добиться того, чтобы:

1. При несовпадении версий мобильное приложение и/или сервер не падали с ошибкой, а корректно обрабатывали такую ситуацию, при необходимости информируя пользователя о дальнейших действиях.
2. Обеспечивалась разумная поддержка предыдущих версий. Так, чтобы можно было обновить сервер и постепенно обновлять мобильные устройства.

Общепринятая [система нумерации версий](https://semver.org/) -- это три числа:

`MAJOR.MINOR.PATCH`

где изменение `MAJOR` версии означает наличие **несовместимых** изменений в функциях приложения, структурах данных, командах API и т.п.

изменение `MINOR` версии показывает на некоторые улучшения, оптимизации в коде программы, не влекущие к нарушению совместимости с существующим кодом.

`PATCH` -- это исправление ошибок или небольшие внутренние исправления в коде, никак не сказывающиеся на внешних интерфейсах программы.

Есть разные стратегии версионирования. Некоторые из них перечислены [здесь](https://www.xmatters.com/blog/blog-four-rest-api-versioning-strategies/).

Заметим, что для вызовов API нас интересует только `MAJOR` версия, т.к. остальные компоненты полной версии по определению не влияют на совместимость.

В чат-боте заработной платы мы применяем версионирование API через включение номера версии в URL запроса, в путь:

`zarobak/v1/getData...`

Стоит подумать надо ли нам кроме версионирования API еще и снабжать метками версий и структуры передаваемых данных.

**Comment by hirurg-lybitel** [comment]
Реализовл схему работы сервера с разными версиями клиентм через прослойку.

Например, в [user controller](https://github.com/stasgm/gdmn-mob/blob/dev/apps/server/src/controllers/user.ts) вместо:
```
  users = await userService.findAll(params); 
```

вызываем:
```
  import * as verUsers from './verUser';
  ...
  switch (version) {
    case '1.0.0':
      users = await verUsers.v1.getUsers(params);
      break;
    case '2.0.0':
     users = await verUsers.v2.getUsers(params);
      break;
    default:
      users = await verUsers.v_last.getUsers(params);
      break;
  }
```

где [verUsers ](https://github.com/stasgm/gdmn-mob/tree/dev/apps/server/src/controllers/verUser)- это прослойка-объект со всеми существующими версиями для user controller.

Такой механизм позволит гибко реагировать на изменения версий клиента любой сложности без грамождения всяких функций типа getUsers_v1, getUsers_v2 и т.д.

**Comment by hirurg-lybitel** [comment]
@stasgm для понимания скажи какие явные минусы у данного варианта
