### ISSUE TITLE
В мобильном продумать и сделать вывод ошибок

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#149]
В библиотеку store добавить хранилище для логирования - logs. Использовать его вместо объекта ошибок errorList  для приложений из папки app. 

Надо продумать:
- в каком виде хранить записи в логе
- как и где выводить для клиента
- как и когда очищать

Например, при синхронизации справочников и документов выполняется много мелких операций, каждая из которых может вернуть ошибку. Но нам не надо выводить ошибку операции сразу. Надо по завершению всей синхронизации предупредить, что были ошибки..и если клиент захочет, чтобы можно было их где-то просмотреть. 
Сейчас список ошибок сохраняется в errorList, а в конце синхронизации выводится окно с предупреждением, что были ошибки. А в начале следующей синхронизации список очищается.

Еще, возможно, будут случаи, когда ошибку сразу надо вывести на экран. 

Обсуждаем в комментариях..

**Comment by stasgm** [comment]
Для вывода ошибки на экран, как я раньше и говорил, надо обернуть слой приложения в компонент который выводил бы обнотипно для любого окна сообщение из стора. 

Так же следует отделять текущие ошибки от ошибок в журнале. Ошибки в приложении, на мой взгляд следует хранить в разделе стора app. Пример: начался процесс загрузки сообщений - в журнал пишем шаги загрузки и если ошибка то пишем её в журнал и дополнительно помещаем в стоп что вызовет о отображение сообщения об ошибке (в компоненте что я выше описал)
