### ISSUE TITLE
Добавить в настройки выбор работы по матрице или нет

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#173]

**Comment by sunnycreature** [comment]
Добавить параметр "Использовать матрицы цен" в настройки приложения.
Учитывать данный параметр при формировании модели товаров.

**Comment by Kostyanaya** [comment]
https://github.com/stasgm/gdmn-mob/commit/0ff5bff490d3ec0d6bd0ddfbe8cfac25267e3d01
