### ISSUE TITLE
Новая инвентаризация. Добавление шапки документа

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#190]
1. Настроить навигацию. Пункты меню: Документы, Справочники, Настройки, Профиль.
2. Описать типы справочников и документов.
Справочники минимум: Типы документов, Подразделения, Организации, Товары.
Документ: Шапка - Номер, Дата, Тип документа - ссылка на справочник типов документа, Подразделение - ссылка на справочник подразделений, Контрагент - ссылка на справочник (подразделения и организации, подумать).
2. При выборе пункта Документы отображать окно со списком всех документов ListScreen. 
По нажатию на кнопку добавления документа ('+' из правого верхнего угла) отображать окно создания\редактирования шапки документа EditScreen. 
Поля для заполнения: Номер, Дата, Тип документа, Подразделение, Контрагент.
3. По нажатию на Сохранить, переходить в окно документа ViewScreen, в котором отображается краткая информацией по документу (с возможностью перейти на окно шапки документа) и списком позиций.

**Comment by DzmitryDon** [comment]
https://github.com/stasgm/gdmn-mob/commit/ca473e9f2aa309608e954102217f2e3333189601

**Comment by sunnycreature** [comment]
Изменить пункт меню Документы на Инветаризация (inventory). Переименовать компоненты.

**Comment by DzmitryDon** [comment]
https://github.com/stasgm/gdmn-mob/commit/6ba224039d9d4c674f66926e7e8a6cde76ad5da6
