### ISSUE TITLE
Новая ивентаризация. Добавление позиции документа

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#195]
4. По нажатию на кнопку добавления позиции документа ('+' из правого верхнего угла) отображать окно выбора из справочника товаров.
5. При выборе товара переходить на окно добавления\редактирования позиции LineScreen. Поля для отображения: наименование товара, цена, остаток, количество. Поля для заполнения: Количество. При сохранении данных переходить в окно документа.

**Comment by DzmitryDon** [comment]
https://github.com/stasgm/gdmn-mob/commit/e46e450f7f0806a5f4b9bb6f6b4ddebdbe7c5436
