### ISSUE TITLE
Новая инвентаризация. Компонент для сканера штрихкодов

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#199]
На экран документа в меню добавить иконку сканера, по нажатию на которую открывать окно для сканирования.
В окне 2 режима:
1. Ожидание сканирования - отображена рамка для сканера, надпись "Наведите рамку на штрихкод". (Когда пользователь наводит на шк, сканер автоматически обрабатывает строку, разбирает ее, находит баркод и товар по нему)
2. После сканирования:
- Если товар по шк найден, то отобразить кнопку "Пересканировать", а ниже вывести кнопку с информацией по товару - наименование, цена, остаток, кол-во, баркод. При нажатии на эту кнопку переходить в окно добавления позиции документа для ввода количества. 
- Если товар не найден, то отобразить кнопку "Пересканировать", а ниже вывести баркод и "Товар не найден". Если нажать на кнопку "Пересканировать", то перейти на окно ожидания сканирования (1).

**Comment by DzmitryDon** [comment]
https://github.com/stasgm/gdmn-mob/commit/be038ec0898d0e68dac18e1d969f62f79aa2be73

**Comment by DzmitryDon** [comment]
https://github.com/stasgm/gdmn-mob/commit/c065a515ec575708c709774d4d51259796b02227
