### ISSUE TITLE
Выбор маршрута

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#201]
В окне карт (MapsScreen) возле наименования текущего маршрута добавить иконку, обозначающую смену маршрута (использовать MaterialCommunityIcons https://icons.expo.fyi/). 

1. Переделать открытие компонента BottomSheet для выбора маршрута не по нажатию на компонент с названием маршрута, а по нажатию на эту иконку.
2. В названии маршрута выводить "№ {номер маршрута} на {дата маршрута} ". Пример: "№ 12 на 02.01.2021". Исправить отображение и в самом окне, и в выпадающем списке.

**Comment by RoverDK** [comment]
[Completed in commit 9351d766a2ab1c867384e85fd8b9281fc5505865.](https://github.com/stasgm/gdmn-mob/commit/9351d766a2ab1c867384e85fd8b9281fc5505865)
