### ISSUE TITLE
Формирование модели с остатками

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#207]
Разработать формирование модели остатков для инвентаризации, на примере формирования модели в агентах, 
Модель должна формироваться при смене справочников: контакты, товары, остатки.
Структуру модели посмотреть в старом проекте инвентаризации на ветке Inventory-honeywell-reader. 
Модель сохранять в локальном хранилище.

**Comment by Kostyanaya** [comment]
https://github.com/stasgm/gdmn-mob/commit/6e826a9eb09c1c46da0347ddfcc88f95e7b19986
