### ISSUE TITLE
Компонент по выбору тмц из остатков вручную

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#212]
Создать компонент по выбору тмц из остатков вручную.
В меню добавить иконку для сканера. 
Отображать информацию по эелементу: остаток, цена, штрихкод.
Добавить поиск по имени и штрихкоду. 
Подключить компонент для добавления товара из окна документа при выборе пункта меню Добавить товар.

**Comment by DzmitryDon** [comment]
https://github.com/stasgm/gdmn-mob/commit/d4fea2a4582367fd0f13fbce0a7bf91246e552d8
