### ISSUE TITLE
Доработать компонент позиции документа

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#213]
Поля для отображения: наименование, цена, остаток, EID - текстовое, количество.
Добавить кнопку Сканировать EID.
По нажатию на данную кнопку вызывать компонент сканера для считывания data matrix штрихкодов.
Заполнять поле EID значением просканированного штрихкода.
Если поле EID заполнено, то справа отображать иконку-крестик, по нажатию на которую, очищать значение поля EID.

**Comment by Kostyanaya** [comment]
https://github.com/stasgm/gdmn-mob/commit/b831c0850c59ff16b932b416a3f863811da1ccc0
