### ISSUE TITLE
Компонент для считывания data matrix штрихкодов

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#214]
Перенести компонент ScanDataMatrix из старой инвентаризации и адаптировать под новое приложение.
Компонент содержит меню (иконка возврата обратно, вкл\выкл фонарика, вкл\выкл вибрации при сканировании), рамку, текст "Наведите рамку на штрихкод".
После сканирования отрисовывать 2 кнопки: Пересканировать и кнопка с текстом из штрихкода. 
При нажатии на кнопку с текстом, закрывать компонент, добавлять текст в поле EID.

**Comment by Kostyanaya** [comment]
https://github.com/stasgm/gdmn-mob/commit/b831c0850c59ff16b932b416a3f863811da1ccc0
https://github.com/stasgm/gdmn-mob/commit/292204edee4c73d048c4a31dc8e5e51564537066

**Comment by Kostyanaya** [comment]
https://github.com/stasgm/gdmn-mob/commit/b831c0850c59ff16b932b416a3f863811da1ccc0
https://github.com/stasgm/gdmn-mob/commit/292204edee4c73d048c4a31dc8e5e51564537066

**Comment by Kostyanaya** [comment]
https://github.com/stasgm/gdmn-mob/commit/b831c0850c59ff16b932b416a3f863811da1ccc0
https://github.com/stasgm/gdmn-mob/commit/292204edee4c73d048c4a31dc8e5e51564537066
