### ISSUE TITLE
Компонент для сканирования штрихкодов в ТСД

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#216]
На основе старого компонента ScanBarcodeReaderScreen и новых изменений добавить компонент для сканера штрихкодов в ТСД.
Отрисовывать компонент, если стоит параметр "Использовать сканер", иначе использовать компонент для камеры.

**Comment by DzmitryDon** [comment]
https://github.com/stasgm/gdmn-mob/pull/218/commits/c9ee2542fa4dc8994f21c23951048ec5d8967f53
