### ISSUE TITLE
Добавление "Неизвестного товара", если товар по шк не найден.

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#219]
Если при сканировании товар не найден, то подставлять товар с ид = 'unknown'. (Из Гедымина будет приходить такой товар в справочник товаров). Цвет кнопки для такого товара оставить красным.

**Comment by Kostyanaya** [comment]
https://github.com/stasgm/gdmn-mob/commit/c7902a600feeea4166ca749f0439875ca20181a6

**Comment by Kostyanaya** [comment]
https://github.com/stasgm/gdmn-mob/commit/c7902a600feeea4166ca749f0439875ca20181a6
