### ISSUE TITLE
Пункт меню Матрицы 

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#231]
Добавить пункт меню Матрицы для просмотра цен по клиентам.
Окно со спсиком клиентов со строкой поиска.
По нажатию на позицию с клиентом переход на окно списка товаров (наименование, цена фсн) со строкой поиска.  
По нажатию на позицию с товаром переход на окно товара с отображением всех цен.

**Comment by Kostyanaya** [comment]
https://github.com/stasgm/gdmn-mob/commit/05632fcae0416d97b5e8d07d4dd0571b6e854c8f
