### ISSUE TITLE
Добавить поиск товара при добавлении тмц в Маршруте в группе

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#328]

**Comment by sunnycreature** [comment]
На будущее.
Добавить чекбокс 'По группам', по умолчанию установлен. При снятии галки отображать весь список товаров с поиском по наименованию.

**Comment by gsbelarus** [comment]
Поиск товара, как минимум, должен вестись по:

1. наименованию
2. штрихкоду

Поле фильтра должно быть одно. Поиск вести по вхождению.

Вместо чек бокса, можно просто в выше дерева групп добавить кнопку **Все товары** и по ней переходить на список товаров без групп.
