### ISSUE TITLE
Обновить expo до 45й версии

### ISSUE THREAD

**Issue by gsbelarus** [stasgm/gdmn-mob#344]
а то гугл ругается:

Your latest production release (12 (0.3.2)) contains SDK issues
GDMN Агент GDMN Агент
Jun 8, 2022 19:34

> The following SDK versions are non compliant with Google Play policies:
> 
>     com.segment.analytics.android:analytics:4.9.4
> 
>     The SDK collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers as described in the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy.
> 
>     Starting from August 8, 2022 midnight (UTC), new app releases containing the SDK version(s) that do not comply with the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy will be blocked from release. You may consider moving to another SDK; removing this SDK; or if available from your SDK provider, upgrading to a policy-compliant version of this SDK that does not include the violating code.
> 
>     According to the information provided by your SDK provider, you may consider upgrading to4.10.1. Please consult the SDK provider for further information.
> 
>     Read through the [User Data](https://support.google.com/googleplay/android-developer/answer/10144311) policy for more details, and how to submit an updated app for review [here](https://support.google.com/googleplay/android-developer/answer/2477981%20#resubmit).
> 
>     If you've reviewed the policy and feel our decision may have been in error, please reach out to our [policy support team](https://support.google.com/googleplay/android-developer/contact/appwarning?ts=sdk).

**Comment by sunnycreature** [comment]
Обновили до 46
