### ISSUE TITLE
Внутреннее перемещение и отвесы

### ISSUE THREAD

**Issue by Kostyanaya** [stasgm/gdmn-mob#385]
- [x] Автоматическое добавление отсканированный позиции
- [x] Отсканированные штрих-коды не должны совпадать
- [x] Суммирование позиций (по id и партиям или только по id)
- [x] Отправление заявок по складам (Гедымин)

**Comment by ilonaand** [comment]
Разбивка заявок по складам Будет осуществляться при экспорте на старые терминалы. На новые мы берем только те, которые уже разбиты по складам и отправлены на старые терминалы, для обеспечения корректной соместной работы с разными типами терминалов на одной экспедиции
