### ISSUE TITLE
Кнопка "Отправить заявку" при статусе заявки "Готов" исчезает в верхнем поле 

### ISSUE THREAD

**Issue by Shakaladkava** [stasgm/gdmn-mob#386]
1. Войти в нужную точку маршрута.
2. Нажать на кнопку "Начать визит".
3. Нажать кнопку "Добавить документ".
4. Оформить заявку, добавляя необходимые продукты и заполняя необходимые поля в самой заявке.
5. Изменить статус с "Черновик" на "Готов", для этого нажать на поле самой заявки и выбрать позицию "Готов" и подтвердить выбор нажатием Галочки.
6. При статусе заявки "Готов" иконка исчезает, и возможности отправить именно эту заявку нет.

**Comment by Kostyanaya** [comment]
https://github.com/stasgm/gdmn-mob/pull/418/commits/6c9c040c7755b4221af77d6ca6e9d611e4f5dab9
