### ISSUE TITLE
Тестирование приложения GDMN Склад

### ISSUE THREAD

**Issue by Kostyanaya** [stasgm/gdmn-mob#401]
1) Изучить [документацию к приложению](https://github.com/stasgm/gdmn-mob/blob/dev/docs/gdmn-gd-movement/docs/README.md)
2) Установить приложение [GDMN Склад](https://play.google.com/store/apps/details?id=com.gsbelarus.gdmovement)
3) Изучить демо режим приложения
4) Подключиться к серверу под пользователем user-inv-test
5) Получить справочники
6) Создать документы прихода и инвентаризации, добавить туда позиции с помощью сканера и из списка остатков
7) Отправить документы в Гедымин

**Comment by Shakaladkava** [comment]
Как подключиться к реальному серверу? Спрашивает код устройства.
