### ISSUE TITLE
При входе в деморежим справочная система находится в недоступном для пользователя месте.

### ISSUE THREAD

**Issue by Shakaladkava** [stasgm/gdmn-mob#403]
Добавить в меню любого мобильного приложения вызов справки.
Добавить переход на документацию в гитхабе.
Аналогично, на экране входа в систему написано, что подробную информацию вы найдете в справочной системе, но где эта система не понятно. Необходимо и там добавить гиперссылку на документацию в гитхабе.

1. Запустить приложение, выбрать демонстрационный режим.
2. Над кнопкой "Начать работу" находится обещание найти подробную информацию в справочной системе. Изменить или дополнить это, так как ни на самой странице, ни в меню нет информации о справочной системе.

На все первые экраны можно добавить пиктограммку с вопросиком, которая будет вести на справку или простототдельную кнопку везде сделать.

**Comment by Kostyanaya** [comment]
https://github.com/stasgm/gdmn-mob/commit/46bd5bb13e20393353823681aa626e99c05646bf
