### ISSUE TITLE
В мобильном приложении "Склад" и "Агент" цифры и заглавные буквы выходят за рамки при заполнении любого документа

### ISSUE THREAD

**Issue by Shakaladkava** [stasgm/gdmn-mob#404]
1. Открыть приложение "Склад", зайти в меню, выбрать "Документы".
2. Открыть любой документ и выбрать "Редактирование документа".
3. Ввести любую информацию (номер, дату или комментарий заглавными буквами) в допустимую строку.
4. Верхняя часть цифр и заглавных букв скрыты рамками формы.

Уточнение: мобильные приложения находятся на Смартфоне Samsung Galaxy A51 SM-A515F/DSM
с разрешением экрана: 2400x1080

![InkedScreenshot_20220805-133525-4_GDMN _LI](https://user-images.githubusercontent.com/109092961/183076810-33845f55-2ac4-4abf-b500-89f6857b3849.jpg)

**Comment by Kostyanaya** [comment]
https://github.com/stasgm/gdmn-mob/pull/418/commits/6c9c040c7755b4221af77d6ca6e9d611e4f5dab9
