### ISSUE TITLE
Подписи к полям ввода

### ISSUE THREAD

**Issue by gsbelarus** [stasgm/gdmn-mob#406]
![image](https://user-images.githubusercontent.com/5175764/184127979-4bb330df-0106-4435-a410-d314c5258124.png)

Кто обрезает? Библиотека? Если да, то надо сокращать, чтобы не обрезалось. И еще всегда когда идет какая-то величина, укажите размерность. Часы, минуты, секунды? тут непонятно.

**Comment by sunnycreature** [comment]
Делаем подписи короче
