### ISSUE TITLE
Во время сканирования, при выборе иконки Вибрация, программа "Склад" (демо версия) совершает аварийное закрытие или зависает.

### ISSUE THREAD

**Issue by Shakaladkava** [stasgm/gdmn-mob#409]
1. Открыть приложение "Склад" (демо версия), зайти в меню, выбрать "Документы".
2. Открыть любой документ и выбрать иконку Штрихкод.
3. Выбрать иконку "Вибрация".
4. Программа перестает реагировать на действия пользователя или происходит аварийное закрытие программы.

Та же проблема появляется и при других путях:

1. Открыть приложение "Склад" (демо версия), зайти в меню, выбрать "Сканирование".
2. Открыть документ и выбрать иконку Штрихкод.
3. Выбрать иконку "Вибрация".
4. Программа перестает реагировать на действия пользователя или происходит аварийное закрытие программы.

**Comment by sunnycreature** [comment]
Добавить permission VIBRATE
