### ISSUE TITLE
Splash окно для приложений

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#412]
Создать варианты splash окон для приложений:
1. GDMN Склад
2. GDMN Отгрузка
3. GDMN Агент
4. GDMN Снабжение

Пожелания: придерживаться основного цвета приложений, гармонично смотрящееся в темной и светлой теме, содержащее название приложения, с логотипом или без него.

**Comment by sunnycreature** [comment]
Можно такие варианты:
1. Только надпись посередине "GDMN Агент"  (GDMN заглавными, название приложения - кириллицей), шрифт более читаемый 
2. Логотип взять в рамку, уменьшить, убрать тень, а справа надпись: сверху GDMN, снизу Агент, или второй варинат GDMN Агент в одну строку

**Comment by sunnycreature** [comment]
Попробовать сделать логотип в квадратной или круглой рамке

**Comment by kdaminikk** [comment]
[gdmn agent icon.pdf](https://github.com/stasgm/gdmn-mob/files/9352810/gdmn.agent.icon.pdf)

**Comment by gsbelarus** [comment]
не надо необычных и детских шрифтов. придерживайтесь простых, строгих
шрифтов так как это деловой софт.

аў, 16 жні 2022, 18:36 карыстальнік Daminik ***@***.***>
напісаў:

**Comment by gsbelarus** [comment]
если хочется именно надпись вместо картинки, то напишите GDMN а под ней
агент. разделите горизонтальной чертой. GDMN можно жирным и побольше.
подогнать обе надписи под одинаковую ширину.

ср, 17 жні 2022, 02:52 карыстальнік AK ***@***.***> напісаў:

**Comment by kdaminikk** [comment]
[gdmn splash.pdf](https://github.com/stasgm/gdmn-mob/files/9384994/gdmn.splash.pdf)

Вот, с правками три варианта

**Comment by sunnycreature** [comment]
Нам понравились такие варианты (с чертой и просто без черты), можно сделать для всех проектов по 2 варианта?
![image](https://user-images.githubusercontent.com/12336960/186639872-4344e62c-bb19-48de-b19f-680194465b8b.png)
![image](https://user-images.githubusercontent.com/12336960/186636923-41ba50eb-b53a-4a6c-8935-b17fe33b98f5.png)

**Comment by kdaminikk** [comment]
[gdmn sell agent (4).zip](https://github.com/stasgm/gdmn-mob/files/9464275/gdmn.sell.agent.4.zip)

Сделал, с вариантами с линией и без

**Comment by sunnycreature** [comment]
Можно нам сделать сплэш для GDMN Снабжение?
А в логотипе GDMN Отгрузка можно букву у заменить на такую, чтобы она была одинаковая по высоте с другими буквами?
