### ISSUE TITLE
Дизайн для окна заявок в приложении GDMN Агент

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#413]
Разработать дизайн для окна заявок в приложении GDMN Агент.
Окно содержит 3 блока: 
1. Шапка документа
2. Позиции документа - список добавленных товаров
3. Итого по документу - колонки Вес, Сумма, Сумма с НДС в разрезе наименований групп товаров, добавленных в документ

Необходимо:
1. Упростить изменение статуса документа с Черновика в Готов и наоборот так, чтобы пользователю не надо было заходить в шапку документа, а чтобы можно было это сделать прямо из окна заявки (сейчас для смены статуса им приходится делать 3 клика - нажать на шапку документа, изменить статус в окне редактирования шапки и нажать на галку, чтобы сохранить изменения).
2. Создать варианты дизайна для итоговой части по документу, учитывая, что:
- групп может быть много, то есть продумать вариант открытия-закрытия блока с группами, оставивь итого по всему документу
- наименования групп могут быть длинными 
- 3 числа - вес, сумма и сумма с ндс, могут быть большими
- перехода на другое окно с итоговыми суммами быть не должно
3. Предложить варианты с общей оптимизацией всего окна в целом (сокращение полей в шапке, иконки и прочее)

**Comment by kdaminikk** [comment]
[Work.pdf](https://github.com/stasgm/gdmn-mob/files/9385072/Work.pdf)

Макет с правками

 * Решил проблему со свайпами добавив лок на блок с главной информацией и тем самым сократил выполнение задачи, с 3 кликов - до одного клика и свайпа
 * Убрал тени с цифр и сделал развернутое меню с более различимыми полями
 * Поработал с тенями
