### ISSUE TITLE
Автоматическое продление сессии

### ISSUE THREAD

**Issue by gsbelarus** [stasgm/gdmn-mob#438]
Пользователя раздражает, не сам факт завершения сессии, а то, что это происходит в процессе работы, в любой произвольный момент времени.

Можно попробовать сделать так:

1. Посмотреть исходники мидлвэра с сессиями и понять, где хранится срок действия сессии. Он будет или зашит в сам куки, или куки будет использоваться как ключ к записи, которая хранится где-то еще. В оперативной памяти, JSON файле и т.п.
2. Ввести комнтанту, содержащую максимальный срок неактивности, в течение которого мы еще сохраняем куки. Например, 72 часа, чтобы сессии спокойно переживали выходные или график работы агента два через два.
3. В мидлвэре, где идет проверка времени жизни сессии, смотреть, если сессия еще валидна и до ее окончания меньше 72 часов, то продлять ее, чтобы было 72 часа. Если сессия не валидна уже (прошло более трех суток с момента последнего обращения), то возвращаем код и приложение пойдет на экран авторизации.
4. Обрабатывать onFocus по которому отправлять на сервер запрос, чтобы проверить/продлить текущую сессию. onFocus поможет нам тем, что когда пользователь не закрывает программу, а сворачивает ее, то при активации, когда сессия истекла, он сразу пойдет на экран ввода пароля, а не в момент когда пойдет какая-то сетевая команда.

Если в исходники мидлвэра трудно вмешаться, то сделать свой мидлвэр на основе исходников текущего.

**Comment by sunnycreature** [comment]
Оставили koa-session, сейчас продливается сессия, и если приложение не работало больше 7 дней, то только тогда запросит логин. А также проверку добавили при разворачивании приложения, но тогда, если вдруг нет сети или сервер не работает, пользователь не сможет войти и работать хотя бы со старыми данными оффлайн.
