### ISSUE TITLE
Доделать в сентябре

### ISSUE THREAD

**Issue by gsbelarus** [stasgm/gdmn-mob#455]
* [x] все библиотеки на новейшие версии обновить
* [x] определять состояние сетевого диалога и хроанить в сторе
* [x] работа в офлайне
* [x] блокировать частую синхронизацию
* [x] т/з по учетным записям, девайсам и т.п.
* [x] все ресурсы (иконки, шрифты, картинки) компилировать в АПК без загрузки из инета

**Comment by gsbelarus** [comment]
Все общение с сервером должно идти через одну функцию/хук, где мы должны определять статус и сохранять его в сторе для использования в других частях программы.

- OK -- запрос к серверу обработан успешно.
- NO_NETWORK -- отсутствует подключение к интернету (надо подумать, стоит ли тут отдельно ловить ситуации самолетного режима или отключенного режима передачи мобильных данных, или нам хватит просто одного статуса)
- TIMEOUT -- сервер недоступен вообще или не может выполнить запрос в установленное время.
- ERROR_500 -- это ошибка внутри сервера. Она не относится к логике программы! Например, сервер пытается записать JSON на диск, а места нет. Происходит исключение и если оно не отловлено нигде, то оно дойдет до клиента в виде HTTP статуса 500. Мы не должны маскировать свои ошибки (относящиеся к логике нашей программы) под код 500. Логическая ошибка всегда возвращается внутри объекта с какими-то данными, текстами, пояснениями. При этом это легитимный ответ сервера, т.е. код HTTP 200.
- ERROR_401 -- это ошибка авторизации. Нет прав, неверный пароль, отсутствует учетная запись и т.п. Пояснение можно переслать в виде объекта.
- ERROR_429 -- пока мы это не обрабатываем, но это превышение лимита на запросы в единицу времени. В будущем, возможно, понадобится.

**Comment by sunnycreature** [comment]
Сейчас организовано так:
Сервер отдает в ответ объект 
- если все прошло без ошибок, то: 
{ 
  status: 200 или 201,
  body: {
     result: true,
     data, 
  }, где data - это объект с возвращаемыми данными, если надо.
- если ответ с ошибкой, например, не найдены данные, нет доступа и т.п., то:
{ 
  status: 200,
  body: {
     result: false,
     error: error.message,
     data: error.name,
     status: error.status,
  },
- если ответ с неизвестной ошибкой:
{ 
  status: 500,
  body: {
     result: false,
     error: error.message || 'Неизвестная ошибка',
     data: 'InnerErrorException',
  }

**Comment by sunnycreature** [comment]
Апи обращается к серверу и если получает ответ, то возвращает объект под каждое апи своего типа, содержащее тип и данные с ответом.
- если result = true, то ответ будет такого типа:
![image](https://user-images.githubusercontent.com/12336960/191339713-a7d6adfb-823d-45f9-9c44-8fe83544dc0c.png)
- если result = false, то ответ будет типа:
![image](https://user-images.githubusercontent.com/12336960/191340400-d675ad3b-67a9-4f9e-ac6c-c3fc3c7fe79c.png)
Если же апи запрос не смог достучаться до сервера, не было интернета или сервер не отвечал, то возвращался тоже ответ с типом 'ERROR'.

**Comment by sunnycreature** [comment]
Я добавлю тогда в тип с ошибкой типы NO_NETWORK, TIMEOUT, ERROR_500, ERROR_40, ERROR_429  
- NO_NETWORK, TIMEOUT определю по типу ошибки от axios
- ERROR_500, ERROR_401 по статусу из ответа от сервера

**Comment by gsbelarus** [comment]
Транспортный уровень должен быть отделен от уровня прикладной логики. Задача транспортного уровня связаться с сервером, передать данные и дождаться ответа. Переданный ответ вернуть пользователю функции в неизменном виде. При возникновении ошибки понять что за она, внести информацию в стор и возможно перейти на некоторый экран.

Так как мобильное приложение и веб приложение имеют разные хранилища, и разные роуты для специальных экранов, то для каждого следует написать свою функцию транспортного уровня.

Пример функции на псевдокоде:

```
function request(method, url, params?, data_для_POST запроса?, typeChecker?) {

  // формируем URL из переданной маски и параметров
  // если они есть. иначе просто берем переданный url  

  try {
    const res = await axios.get(url);

    // если задана функция проверки типа
    // объекта, который вернул сервер, то вызываем ее
    // чтобы убедиться, что нам пришли правильные данные, а не ерунда

    // выставим в сторе состояние связи по сети ОК

    return res;
  } catch (e) {

    // обрабатываем ошибки отсутствия сети
    // или отсутствия сервера

   // заносим в стор
   // при необходимости переходим на другой экран
   // например при ошибке с правами доступа 
  }   

  return undefined;
}
```

тогда функция API становится простой. Например:

```
function _apiGetDevice(transportFn, deviceId) {
  
  const res = await transportFn('GET', 'http://server.com/getdevice/:deviceId', { deviceId });
 
  if (res) {
    // получили данные устройства. можем делать с ними что-то
  }
}
```

Для того, чтобы не таскать за собой транспортную функцию просто сделаем HOF:

```
  const apiGetDevice = (deviceId) => _apiGetDevice(request, deviceId)
```

определять HOF функции надо будет по отдельности  для мобильного и для веба,
потому что у них будут разные транспортные функции.

можно для этого написать еще одну функцию, а можно просто руками присваивать как показано выше.
