### ISSUE TITLE
Общая функция запроса к серверу с обработкой ошибок и тайм-аута

### ISSUE THREAD

**Issue by gsbelarus** [stasgm/gdmn-mob#460]
Задача обернуть вызов axios в свою асинхронную функцию, которая бы корректно обрабатывала ситуации:

1. отсутствия сети
2. отсутствия реакции сервера (превышен заданный тайм-аут ожидания ответа сервера. Использовать стандартный AbortController)
3. ошибки клиента и сервера (HTTP коды 4хх, 5хх)
4. проверяла пришедшие данные на корректность 
5. могла десериализовать их (преобразовать полученный объект в объект, нужный программе. Например, заменив ИД объекта на ссылку на сам объект. Или преобразовать объект из одной структуры в другую, если у нас возникнет разница в версиях мобильного приложения и сервера)

Параметры функции передаются в виде объекта типа _IRequestParams_:

```ts
/** Валидатор проверяет полученные данные на корректность. В случае ошибки генерирует исключение. */
type Validator = (data: Object) => void;

/** Десериализатор, если есть, может одновременно являться  и валидатором. */
type Deserializer = (data: Object) => Object;

interface IURLParams {
  [paramName: string]: string | number;
};

interface IRequestParams {
  /** method HTTP. По умолчанию подставляется GET. */
  method?: 'GET' | 'POST' | 'PUT' | 'DELETE'; 
  /** Базовый УРЛ. Если задан, то итоговый УРЛ получается слиянием базового и УРЛ. Может содержать маску.*/
  baseUrl?: string;
  /** Адрес. Может содержать маску.*/
  url: string;
  /** Параметры, если url и/или baseUrl используют маску. Кодируются в строку через URL Encoder. */
  params?: IURLParams;
  /** Данные для передачи методом POST. */
  data?: Object;
  /** Функция проверки полученных данных. Проверяются только результаты запроса со статусом 2ХХ */
  validator?: Validator;
  /** Функция преобразования полученных данных в нужный тип объекта */
  deserializer?: Deserializer;
  /** Тайм аут в секундах */
  timeout?: number;
}
``` 

Функция возвращает объект следующего типа:

```ts
type RequestResult = IServerResponseResult | IServerUnreacheableResult | IErrorResult;

interface IServerResponseResult {
  /** 2xx, 4xx, 5xx */
  result: 'OK' | 'CLIENT_ERROR' | 'SERVER_ERROR';
  response: {
    /** HTTP response status */
    status: number;
    data?: Object;
  } 
};

interface IServerUnreacheableResult {
  result: 'NO_CONNECTION' | 'TIMEOUT';
};

/** Возвращается, когда произошло исключение при проверки типа, десериализации или вообще в процессе работы */
interface IErrorResult {
  result: 'INVALID_DATA' | 'ERROR';
  message?: string;
};
```

Замечания:

1. Функцию и типы к ней сделать как дженерик, чтобы прокидывать результирующий тип объекта ответа с данными.
1. Функцию следует поместить в общую библиотеку и использовать в мобильном и веб интерфейсе для сетевых обращений. При этом в каждом проекте вокруг нее следует обернуть свою функцию или хук, который будет в зависимости от полученного результата выставлять соответствующее состояние в хранилище и передавать полученные данные дальше, для обработки. 
2. При успешном обращении к серверу функция ожидает получить объект или ничего. Преобразования JSON текста в объект не является задачей данной функции и происходит раньше на уровне мидлвэра в express/koa.
3. Если функция-валидатор указана, но от сервера не пришел объект с данными, то возвращается код INVALID_DATA и сообщение "Empty server response".

**Comment by gsbelarus** [comment]
1. Назовем функцию, описанную выше rr -- robust request. Помещаем ее в общую библиотеку.
2. Она не нуждается в try..except т.к. все исключения обрабатывает внутри себя. Просто пишем `await rr()`, получаем результат и работаем с ним.
3. В веб приложении и мобильном приложении мы по своему обрабатываем, например, ситуацию отсутствия сети или проблемы с авторизацией пользователя. Поэтому в каждом проекте пишем свою обертку с теми же параметрами. Назовем ее, например cr -- custom request.
4. Функции API размещаются в общей библиотеке. На вход каждая функция принимает дополнительно функцию сетевого запроса и вызывает ее, а не напрямую обращается к axios.
5. Для того чтобы везде по коду не усложнять вызов функций API постоянной передачей внутрь сетевой функции, можно в начале проекта обернуть каждую функцию внешней функцией, которая будет принимать обычные параметры, добавлять от себя сетевую функцию и вызывать обернутый вызов API.

**Comment by sunnycreature** [comment]
https://github.com/stasgm/gdmn-mob/commits/syncInfo3
