### ISSUE TITLE
Попробовать не прописывать непосредственный IP адрес

### ISSUE THREAD

**Issue by gsbelarus** [stasgm/gdmn-mob#472]
В параметрах подключения, вместо цифр указывать:

http://agent.gdmn.app:<номер порта>

Для склада я сделаю другой адрес, чтобы мы потом смогли разделить их на разные сервера.

**Comment by sunnycreature** [comment]
У нас все приложения на одном IP, назовите более общим названием

**Comment by ilonaand** [comment]
Кстати я попробовала этот адрес на нашей базе бро в гедемине прописать вместо цифр - работает
