### ISSUE TITLE
Сделать окно выбора товарных групп

### ISSUE THREAD

**Issue by stasgm** [stasgm/gdmn-mob#49]
Со слов Илоны

При выборе товаров при нажатии на + должны вылезать не товары, а список из групп, в которых нет парента. Верхняя должна быть в раскрытом виде, остальные – в закрытом, при нажатии на группу должна раскрываться эта, остальные закрываться. Все в одном окне. При нажатии на группу список товаров по этой группе. Важно: следующий плюс должен сразу переходить в группу, где брали в прошлый раз. И возможность открыть список групп для выбора другой. БЕЗ ЭТОГО бройлерам можно даже не показывать. Они просто не смогут работать с их справочником

**Comment by LenaBuraja** [comment]
f08a036
