### ISSUE TITLE
Обработка опреации получение текущего местоположения

### ISSUE THREAD

**Issue by LenaBuraja** [stasgm/gdmn-mob#51]
Не на всех устройствах определение текущего местоположения работает корректно. Иногда выдаёт предупреждение. Геолокация включена.
![photo_2021-06-08_12-29-24](https://user-images.githubusercontent.com/21971371/121161025-44fae200-c855-11eb-97e9-f34143eaeb2c.jpg)

**Comment by stasgm** [comment]
Добавлена обработка исключений
