### ISSUE TITLE
Поле для ввода числа (калькулятор)

### ISSUE THREAD

**Issue by gsbelarus** [stasgm/gdmn-mob#529]
Сейчас при переходе в такое поле появляется стандартная клавиатура для ввода чисел от Андроида. Предлагается создать свой визуальный компонент по аналогии с калькулятором, который применяется для ввода числовых значений в Гедымине. С учетом специфики и размера экрана мобильного устройства.

Калькулятор планируется вызывать по нажатию на пиктограмму в поле с числом. Само поле при этом не редактируемое и служит только для отображения числа:

![image](https://user-images.githubusercontent.com/5175764/209571989-a8dc0ad0-abe4-4ff3-b3b0-182c65e0dc94.png)

У калькулятора будет два режима работы:

1. Ввод числа
2. Ввод количества в заданных единицах (например, упаковках) и подсчет итогового значения.

Ввод числа:

![image](https://user-images.githubusercontent.com/5175764/209572070-2840d558-8c61-4e7a-92ee-000624a830a9.png)

В этом режиме калькулятор открывается как диалоговое окно и занимает практически весь экран мобильного устройства. Компонент содержит следующие элементы:

1. В заголовке показываем название поля, которое заполняем.
2. В правом верхнем углу может присутствовать пиктограммка справки, если последняя указана в пропсах компонента. При нажатию на пиктограммку открывается диалог с текстом подсказки.
3. Поле с отображением числа. Курсора нет. Редактировать в поле нельзя.
4. Выше поля с числом выводятся операнды арифметических операций и сами операции, если пользователь вызывает несколько операций для выполнения расчета. Как это работает см. в стандартном калькуляторе Windows 10.
5. Основное пространство компонента занимают 20 кнопок для ввода цифр, десятичной точки, арифметических операций, смены знака. Редактирование осуществляется с помощью двух кнопок: С -- полная очистка до нуля или минимального значения, если оно больше нуля. Стрелка влево -- удаление последнего символа. Если на экране остался только один символ, то стрелка влево действует аналогично клавише С.
6. Внизу компонента две кнопки -- Отмена (закрывает калькулятор без изменения значения поля), Ок -- закрывает калькулятор и записывает в поле значение. Нажатие на клавишу =, если нет введенных арифметических действий для вычисления, закрывает калькулятор аналогично кнопке Ок.

Пропсы компонента:

1. DecDigits?: number -- максимальное количество цифр после десятичной точки. 0 -- можно вводить только целые числа и кнопка для ввода десятичной точки не активна. По-умолчанию -- 2.
2. MinValue?: number -- минимально допустимое значение. При попытке ввести число меньше -- оно заменяется на минимальное значение. Может быть не задано.
3. MaxValue?: number -- аналогично для макс значения.

Режим работы с выбором количества упаковок:

![image](https://user-images.githubusercontent.com/5175764/209575672-4eb8eda7-86b4-45f1-b99d-81d9727b4ec5.png)

1. В этом режиме пропсами передается массив упаковок. Каждый объект содержит ид, наименование для отображения на экране и значение.
2. В верхней части калькулятора выводим список упаковок. Одна из них выбрана и подсвечивается соответствующим образом. Пользователь может выбрать любую упаковку. 
3. Ниже идет поле ввода числа. В данном случае это количество упаковок. Может быть и дробным значением, в зависимости от настроек калькулятора.
4. Ниже поле Итого -- количество упаковок, умноженное на размер одной упаковки. Итого нельзя редактировать непосредственно.

Пропсы компонента:

1. Все теже, что и для калькулятора, плюс:
2. DecDigitsForTotal?: number -- количество десятичных знаков для итогового значения.

**Comment by sunnycreature** [comment]
1. Здесь важно минимум нажатий. Сейчас это 1. выбор упаковки, 2. ввод количества, 3. сохранение. Действие для открытия\закрытия калькулятора будет лишним.
2. Мы не знаем вес упаковки. Поэтому можем предоставить возможность вручную вводить формулу для расчета, чтобы облегчить расчет (мы даже точно не знаем, надо ли это им)

Надо оставить окно как есть, только упаковку отобразить над количеством, а под количеством вывести встроенный калькулятор, у которого свой input компонент. Если введены цифры, то подставлять их в поле Количество, если есть арифметичские символы, то количество будет подставлятся после нажатия на кнопку "=".
