### ISSUE TITLE
Синхронизация. Деление файлов со справочниками больших объемов

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#567]
Так как файлы сообщений со справочниками могут быть большими, надо сохранять их частями. 

- В Гедымине формировать несколько файлов сообщений для справочников больших объемов, в каждом из них указывая некий параметр Порядковый номер файла, что файлов несколько. 
- В мобильном добавить возможность дозапись данных к уже загруженному справочнику, если сообщение содержит параметр Порядковый номер файла.

**Comment by gsbelarus** [comment]
1. Разбивать или нет большую передачу на последовательность сообщений решает разработчик серверного приложения.
2. Каждое сообщение в последовательности может иметь свой размер (свое количество записей, если передается массив).
3. Если передача данных разбивается на последовательность сообщений, то в заголовочную часть сообщения (там, где у нас передается номер версии структуры данных) добавляются поля:
  * multipartId: uuid -- идентификатор последовательности. общий у всех сообщений в последовательности.
  * multipartSeq: number -- номер сообщения в последовательности, начиная с 0.
  * multipartEOF?: boolean -- true, если это последнее сообщение в последовательности.
4. `multipartEOF` обязательно должно присутствовать в последнем сообщении. В остальных -- присутствие этого поля опционально.
5. Клиент, получая сообщение(я) у которого присутствует признак `multipartId` помещает его в хранилище, но не обрабатывает, пока не будет получено сообщение, помеченное как последнее в последовательности.
6. Клиент ведет учет времени получения сообщения с `multipartId` в разрезе этих идентификаторов. Т.е. при получении сообщения из последовательности, время для идентификатора последовательности добавляется или обновляется.
7. **Ситуация: все сообщения успешно получены.** Получив сообщение, помеченное как последнее в последовательности, клиент проверяет наличие всех номеров в последовательности. Если все сообщения были приняты, то: 
  * удаляется информация о времени для данного `multipartId`.
  * сообщения из последовательности обрабатываются так, как будто было получено одно большое сообщение (т.е. данные/массивы сливаются в один поток). 
9. **Ситуация: потеряно сообщение из последовательности.** Если получено сообщение, помеченное как последнее в последовательности, но в самой последовательности пропущен хотя бы один номер, то вся последовательность не обрабатывается и удаляется из памяти, вместе с информацией о времени ее получения. В лог заносится сообщение об ошибке.
10. **Ситуация: последовательность сообщений не передана в установленный промежуток времени.** При каждой синхронизации с сервером, дополнительно, мы проверяем информацию о времени приема последовательностей. Если присутствуют идентификаторы последовательностей, с момента последнего сообщения в которых прошло более заданного промежутка (например, 1 час), то вся недопринятая последовательность удаляется, информация о времени удаляется и в лог помещается ошибка.
