### ISSUE TITLE
Доабвление нового устройства пользователю

### ISSUE THREAD

**Issue by Kostyanaya** [stasgm/gdmn-mob#675]
- [ ] В админке при добавлении нового устройства пользователю сразу подставлять биндингу статус устройства
- [ ] На сервере не давать залогиниться, если статус устройства не равен Активному
- [ ] Если менять статус устройства через админку, то что с биндингами?

**Comment by sunnycreature** [comment]
В админке статус биндинга может быть либо Заблокировано либо равно статусу устройства. 
При изменении статуса устройства биндингу менять статус на такой же, если он не Заблокировано.
