### ISSUE TITLE
Склад. Документ Сверка

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#677]
Новый пункт меню для документа "Сверка".

Шапка: Номер, дата, подразделение (обязательное), комментарий.
Позиции: баркод, товар.

Сканируем - в окне отображается 2 кнопки, одна - Пересканировать, вторая - с информацией о ШК. 

Если найден товар с таким ШК и он есть в остатках, то на второй кнопке отобразится название товара, цена и остаток. По нажатию на нее или кнопку Пересканировать, переходим снова в окно сканирования. 

Если товар с таким ШК не найден или его нет в остатках, то на кнопке отобразится только ШК или название товара. По нажатию на эту кнопку создастся позиция с таким ШК или товаром и отрисуется снова окно сканирования. Можно добавить звуковое сообщение "Товар не найден" или "Нет в остатках".

После завершения всей сверки документ отправляем в документ Переучет в Гедымине, а там специалист обрабатывает данные по ненайденным товарам или товарам без остатка, как ему надо.

**Comment by sunnycreature** [comment]
Новый пункт меню для документа "Сверка".

Шапка: Номер, дата, подразделение (обязательное), комментарий.
Позиции: баркод, товар, привязан (логическое).

Сканируем:

- Если найден товар с таким ШК, то в окне отображается 2 кнопки, одна - Пересканировать, вторая - с информацией о товаре (наименование товара, цена и остаток).

По нажатию на кнопку с информацией о товаре создается позиция с данным товаром и снова отрисовывается окно сканирования. 

По нажатию на кнопку Пересканировать, переходим в окно сканирования.

- Если товар с таким ШК не найден, то в окне отображается 3 кнопки, одна - Пересканировать, вторая - с информацией о ШК, третья - Привязать.

По нажатию на кнопку с ШК создастся позиция с таким ШК.  

По нажатию на кнопку "Привязать" откроется окно выбора товара из списка, после выбора товара создастся позиция с таким ШК и товаром, свойство "Привязан" = true,  и отрисуется снова окно сканирования. Можно добавить звуковое сообщение "Товар не найден".  

По нажатию на кнопку Пересканировать, переходим в окно сканирования.

После завершения всей сверки документ отправляем в документ Переучет в Гедымине, а там специалист обрабатывает данные по ненайденным товарам.

**Comment by MAliaksandr** [comment]
Все согласно логики. 
Единственное, что я могу добавить - поиск товара, когда привязываем, должен быть не только по наименованию, но например и по части ШК(если такое возможно). К примеру: вносим первые 6-8 цифр 13значного кода, чтобы упростить поиск. Если ничего соответствующего не находим, тогда по наименованию(или его части)
