### ISSUE TITLE
Сортировка маршрутов по дате  

### ISSUE THREAD

**Issue by sunnycreature** [stasgm/gdmn-mob#70]

**Comment by LenaBuraja** [comment]
5e01232

**Comment by stasgm** [comment]
@sunnycreature И что это за сортировка такая? Сверху теперь всегда будут самые старые  т.е. 1 число потом 2 потом 3 и потом только 14, т.е. сегодня

**Comment by stasgm** [comment]
https://github.com/stasgm/gdmn-mob/issues/70
