### ISSUE TITLE
Причина возврата закрывается клавиатурой

### ISSUE THREAD

**Issue by ilonaand** [stasgm/gdmn-mob#78]
На небольшом экране при редактировании причины возврата поле полностью перекрывается выезжающей клавиатурой

**Comment by stasgm** [comment]
[Почитать тут](https://martinadamko.medium.com/the-hidden-text-input-of-react-native-apps-7b60a03b1fa3)

[Посмотреть компонент](https://github.com/APSL/react-native-keyboard-aware-scroll-view)
