### ISSUE TITLE
Сделать компонент для выбора позиций из списка

### ISSUE THREAD

**Issue by stasgm** [stasgm/gdmn-mob#85]
1. Должен быть placeholder т.е. в компоненте текст "Выберите организацию..." после выбора лейбл Организация
2. Поле обязательное (rquired) или нет (настраивается свойством). И цветом фона указывается пользователю что оно обязательное 
3. Свойством (editable) указывать доступно ли для изменения. И цветом фона указывается пользователю что оно недоступно для изменения
3. Посмотреть в других программах как выводится наименование если не помещается по ширине

**Comment by ilonaand** [comment]
4. Добавить возможность снять уже выбранные значения и не выбрать ничего
