### ISSUE TITLE
Для проверки устройства при подключении в моб приложении добавить отдельный endpont в auth

### ISSUE THREAD

**Issue by stasgm** [stasgm/gdmn-mob#97]
/api/devices/:id возвращает информацию по устройству в случае если есть права у залогиненного пользователя.

Необходимо добавить public endpoint для проверки устройства, активировано или нет.

Определить какие типы ответа от сервера могут быть и куда отправляет нас каждый ответ (например blocked - остаёмся в окне подключения и отображаем как ошибку, в случае active - переходим  на экран входа пользователя, non-activated - на окно активации).

(пример /api/auth/devicestatus/:id возвращает ['NON-ACTIVATED' | 'ACTIVE' | 'BLOCKED'])
В этот end point передаём uid устройства (который сохраняется в стейт, а стейт сохраняется на диске устройства)

**Comment by sunnycreature** [comment]
При первом подключении нового устройства (когда в хранилище нет uid) не отправлять запрос, а сразу переходить на окно активации кода.

**Comment by sunnycreature** [comment]
В хранилище добавлено свойство connectionStatus: 'not-connected' | 'connected' | 'not-activated'. DeviceId хранится в настройках мобильного после активации, при подключении, проверяем статус устройства по этому ид.     
Если connectionStatus = 'not-connected', то переходим на окно с подключеним
    Если connectionStatus = 'connected' и user undefined то переходим на окно входа пользователя
    Если connectionStatus = 'connected' и есть user, то переходим на окно с компаниями
    Если connectionStatus = 'not-activated', то переходим на окно активации устройства
